import { HardDrive, MailPlus, MoreHorizontal, Plus, Trash2 } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { trpc } from '../trpc'
import { Modal } from '../components/Modal'
import { StatusPill } from '../components/StatusPill'

export function Mailboxes() {
  const utils = trpc.useContext(); const list = trpc.mailbox.list.useQuery(); const create = trpc.mailbox.create.useMutation({ onSuccess: () => { void utils.mailbox.list.invalidate(); setOpen(false) } }); const remove = trpc.mailbox.remove.useMutation({ onSuccess: () => void utils.mailbox.list.invalidate() }); const [open, setOpen] = useState(false)
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); create.mutate({ address: String(data.get('address')), password: String(data.get('password')), displayName: String(data.get('displayName')), imapHost: String(data.get('imapHost') || '') || undefined, quotaLimit: Number(data.get('quotaLimit')) }) }
  return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">账号管理</p><h1>邮箱账号</h1><p>管理当前服务下的邮箱地址和存储配额。</p></div><button className="primary-button" onClick={() => setOpen(true)}><Plus size={17} />创建邮箱</button></div>
    <section className="panel table-panel"><div className="table-toolbar"><div><strong>{list.data?.list.length || 0} 个邮箱</strong><span>可用域名：{list.data?.domains.join('、') || '未配置'}</span></div><span className="storage-summary"><HardDrive size={16} /> 已使用 {list.data?.totalUsed || 0} MB</span></div><div className="responsive-table"><table><thead><tr><th>邮箱地址</th><th>状态</th><th>存储配额</th><th>未读</th><th>创建时间</th><th aria-label="操作" /></tr></thead><tbody>{list.data?.list.map(box => { const percent = Math.round(box.quotaUsed / box.quotaLimit * 100); return <tr key={box.id}><td><div className="address-cell"><span><MailPlus size={17} /></span><div><strong>{box.address}</strong><small>{box.displayName || '未命名'}</small></div></div></td><td><StatusPill active={box.status === 'active'}>{box.status === 'active' ? '正常' : '停用'}</StatusPill></td><td><div className="table-quota"><span>{box.quotaUsed} / {box.quotaLimit} MB</span><div className="progress"><i style={{ width: `${percent}%` }} /></div></div></td><td><b className={box.unread ? 'count-badge' : ''}>{box.unread}</b></td><td>{new Date(box.createdAt).toLocaleDateString('zh-CN')}</td><td><button className="icon-button danger" title="删除邮箱" onClick={() => confirm(`确定删除 ${box.address}？`) && remove.mutate({ id: box.id })}><Trash2 size={16} /></button></td></tr> })}</tbody></table></div>{!list.isLoading && !list.data?.list.length && <div className="empty-state"><MailPlus size={32} /><strong>还没有邮箱账号</strong><span>创建第一个账号开始接收邮件。</span></div>}</section>
    {open && <Modal title="创建邮箱账号" onClose={() => setOpen(false)}><form className="form-stack" onSubmit={submit}><label>邮箱地址<input name="address" type="email" placeholder="name@example.com" required /></label><label>显示名称<input name="displayName" placeholder="例如：客户支持" /></label><label>IMAP 主机（可选）<input name="imapHost" placeholder="留空自动使用 mail.你的域名" /></label><div className="form-grid"><label>邮箱密码<input name="password" type="password" required /></label><label>配额 (MB)<input name="quotaLimit" type="number" min="128" max="102400" defaultValue="2048" required /></label></div>{create.error && <p className="form-error">{create.error.message}</p>}<footer><button type="button" className="secondary-button" onClick={() => setOpen(false)}>取消</button><button className="primary-button" disabled={create.isLoading}>{create.isLoading ? '创建中...' : '创建邮箱'}</button></footer></form></Modal>}
  </div>
}
