import { Archive, ChevronLeft, Mail as MailIcon, PenLine, RefreshCw, Reply, Search, Send, Star, Trash2 } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { trpc } from '../trpc'
import { Modal } from '../components/Modal'

export function Mail() {
  const [search, setSearch] = useState(''); const [selectedId, setSelectedId] = useState<string>(); const [compose, setCompose] = useState(false); const utils = trpc.useContext(); const list = trpc.mail.list.useQuery({ page: 1, pageSize: 50, search }, { keepPreviousData: true }); const selectedMail = list.data?.items.find(mail => mail.id === selectedId); const detail = trpc.mail.detail.useQuery({ uid: selectedMail?.uid || 0, mailbox: selectedMail?.mailbox }, { enabled: Boolean(selectedMail) }); const flags = trpc.mail.updateFlags.useMutation({ onSuccess: () => { void utils.mail.invalidate() } }); const remove = trpc.mail.delete.useMutation({ onSuccess: () => { setSelectedId(undefined); void utils.mail.list.invalidate() } }); const send = trpc.mail.send.useMutation({ onSuccess: () => setCompose(false) })
  useEffect(() => { if (selectedId === undefined && list.data?.items[0]) setSelectedId(list.data.items[0].id) }, [list.data, selectedId])
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); send.mutate({ to: String(data.get('to')), subject: String(data.get('subject')), text: String(data.get('text')) }) }
  const current = detail.data
  return <div className="mail-page"><aside className={`inbox-pane ${selectedId !== undefined ? 'mobile-hidden' : ''}`}><div className="inbox-head"><div><p className="eyebrow">统一收件箱</p><h1>邮件</h1></div><button className="primary-icon-button" title="写邮件" onClick={() => setCompose(true)}><PenLine size={18} /></button></div><div className="search-box"><Search size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="搜索发件人或主题" /><button title="刷新" onClick={() => void list.refetch()}><RefreshCw size={15} /></button></div><div className="mail-list inbox-list">{list.data?.items.map(mail => <button key={mail.id} className={`mail-row ${selectedId === mail.id ? 'selected' : ''} ${!mail.seen ? 'unread' : ''}`} onClick={() => { setSelectedId(mail.id); if (!mail.seen) flags.mutate({ uid: mail.uid, mailbox: mail.mailbox, action: 'read' }) }}><span className="avatar">{(mail.from.name || mail.from.address).slice(0, 1).toUpperCase()}</span><span className="mail-primary"><strong>{mail.from.name || mail.from.address}</strong><span>{mail.subject}</span><small>{mail.preview || mail.from.address}</small></span><time>{shortDate(mail.date)}</time>{mail.flagged && <Star size={13} fill="currentColor" className="starred" />}</button>)}</div>{!list.isLoading && !list.data?.items.length && <div className="empty-state"><MailIcon size={28} /><strong>没有找到邮件</strong><span>尝试更换搜索条件。</span></div>}</aside>
    <main className={`message-pane ${selectedId === undefined ? 'mobile-hidden' : ''}`}>{current ? <><div className="message-toolbar"><button className="icon-button mobile-back" onClick={() => setSelectedId(undefined)} title="返回"><ChevronLeft size={20} /></button><div><button className="icon-button" title="回复" onClick={() => setCompose(true)}><Reply size={17} /></button><button className="icon-button" title="标记重要" onClick={() => flags.mutate({ uid: current.uid, mailbox: current.mailbox, action: current.flagged ? 'unflag' : 'flag' })}><Star size={17} fill={current.flagged ? 'currentColor' : 'none'} /></button><button className="icon-button" title="归档"><Archive size={17} /></button></div><button className="icon-button danger" title="删除" onClick={() => confirm('确定删除这封邮件？') && remove.mutate({ uid: current.uid, mailbox: current.mailbox })}><Trash2 size={17} /></button></div><article className="message-content"><header><h2>{current.subject}</h2><div className="sender-line"><span className="avatar large">{(current.from.name || current.from.address).slice(0, 1).toUpperCase()}</span><div><strong>{current.from.name || current.from.address}</strong><span>{current.from.address} 发给 {current.to.map(v => v.address).join(', ')}</span></div><time>{new Date(current.date).toLocaleString('zh-CN')}</time></div></header><div className="message-body">{current.text || current.preview}</div>{current.attachments.length > 0 && <div className="attachments"><strong>{current.attachments.length} 个附件</strong>{current.attachments.map(a => <div key={a.filename}><MailIcon size={17} /><span>{a.filename}</span><small>{formatSize(a.size)}</small></div>)}</div>}</article></> : <div className="message-placeholder"><MailIcon size={36} /><strong>选择一封邮件</strong><span>邮件内容将在这里显示。</span></div>}</main>
    {compose && <Modal title="写邮件" onClose={() => setCompose(false)} width={620}><form className="form-stack" onSubmit={submit}><label>收件人<input name="to" type="email" defaultValue={current?.from.address} required /></label><label>主题<input name="subject" defaultValue={current ? `Re: ${current.subject}` : ''} required /></label><label>正文<textarea name="text" rows={9} required /></label>{send.error && <p className="form-error">{send.error.message}</p>}<footer><button type="button" className="secondary-button" onClick={() => setCompose(false)}>取消</button><button className="primary-button" disabled={send.isLoading}><Send size={16} />{send.isLoading ? '发送中...' : '发送'}</button></footer></form></Modal>}
  </div>
}
function shortDate(value: string) { const date = new Date(value); return date.toDateString() === new Date().toDateString() ? date.toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }) : date.toLocaleDateString('zh-CN', { month: 'numeric', day: 'numeric' }) }
function formatSize(bytes: number) { return bytes > 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.ceil(bytes / 1024)} KB` }
