import { BellRing, Braces, Clock3, Eye, Loader2, Save, Send, ShieldCheck } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { NotificationSettings } from '@mail/shared'
import { trpc } from '../trpc'

const variables = ['{{subject}}', '{{from.name}}', '{{from.address}}', '{{date}}', '{{to}}', '{{body.text}}', '{{attachments.length}}', '{{url}}']
export function Notifications() {
  const query = trpc.notification.get.useQuery(); const [form, setForm] = useState<NotificationSettings>(); const save = trpc.notification.save.useMutation({ onSuccess: data => setForm(data) }); const preview = trpc.notification.preview.useMutation(); const test = trpc.notification.test.useMutation()
  useEffect(() => { if (query.data) setForm(query.data) }, [query.data])
  if (!form) return <div className="page-loading"><Loader2 className="spin" />正在载入通知设置</div>
  function update<K extends keyof NotificationSettings>(key: K, value: NotificationSettings[K]) { setForm(current => current ? { ...current, [key]: value } : current) }
  return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">自动化</p><h1>Telegram 通知</h1><p>配置新邮件的推送内容、筛选条件和静默时段。</p></div><div className="heading-actions"><button className="secondary-button" onClick={() => test.mutate({ botToken: form.botToken, chatId: form.chatId })} disabled={test.isLoading}><Send size={16} />发送测试</button><button className="primary-button" onClick={() => save.mutate(form)} disabled={save.isLoading}><Save size={16} />保存设置</button></div></div>
    {(save.isSuccess || test.isSuccess) && <div className="success-banner"><ShieldCheck size={17} />{save.isSuccess ? '设置已保存' : '测试通知已发送'}</div>}{(save.error || test.error) && <div className="error-banner">{save.error?.message || test.error?.message}</div>}
    <div className="settings-grid"><div className="settings-main"><section className="panel settings-section"><div className="section-title"><span className="section-icon"><BellRing size={18} /></span><div><h2>推送状态</h2><p>控制新邮件通知和目标会话。</p></div><label className="switch"><input type="checkbox" checked={form.enabled} onChange={e => update('enabled', e.target.checked)} /><i /></label></div><label className="field">Telegram Bot Token<input type="password" value={form.botToken} onChange={e => update('botToken', e.target.value)} placeholder="123456:AA..." autoComplete="off" /><span>Token 仅保存在服务端，不会返回完整内容。</span></label><label className="field">Telegram Chat ID<input value={form.chatId} onChange={e => update('chatId', e.target.value)} placeholder="例如：-1001234567890" /></label></section>
      <section className="panel settings-section"><div className="section-title"><span className="section-icon code"><Braces size={18} /></span><div><h2>通知模板</h2><p>使用 Handlebars 变量定制推送文本。</p></div></div><div className="template-tools">{variables.map(variable => <button key={variable} onClick={() => update('template', `${form.template}${form.template.endsWith('\n') ? '' : '\n'}${variable}`)}>{variable}</button>)}</div><textarea className="code-editor" value={form.template} onChange={e => update('template', e.target.value)} rows={12} spellCheck={false} /><div className="editor-footer"><label>正文预览字数<input type="number" min="0" max="4000" value={form.previewLength} onChange={e => update('previewLength', Number(e.target.value))} /></label><button className="secondary-button" onClick={() => preview.mutate({ template: form.template, previewLength: form.previewLength })}><Eye size={16} />生成预览</button></div></section>
      <section className="panel settings-section"><div className="section-title"><span className="section-icon clock"><Clock3 size={18} /></span><div><h2>通知规则</h2><p>留空筛选条件表示通知所有新邮件。</p></div></div><div className="form-grid"><label className="field">关键词<span>使用英文逗号分隔</span><input value={form.keywords.join(', ')} onChange={e => update('keywords', split(e.target.value))} placeholder="账单, 告警, 验证码" /></label><label className="field">发件人白名单<span>使用英文逗号分隔</span><input value={form.senderAllowlist.join(', ')} onChange={e => update('senderAllowlist', split(e.target.value))} placeholder="@example.com, admin@site.com" /></label></div><div className="quiet-row"><label className="checkbox-label"><input type="checkbox" checked={form.quietEnabled} onChange={e => update('quietEnabled', e.target.checked)} />启用静默时段</label><div><input type="time" value={form.quietStart} onChange={e => update('quietStart', e.target.value)} disabled={!form.quietEnabled} /><span>至</span><input type="time" value={form.quietEnd} onChange={e => update('quietEnd', e.target.value)} disabled={!form.quietEnabled} /></div></div></section></div>
      <aside className="preview-panel"><div className="preview-heading"><div><span className="telegram-mark"><Send size={17} /></span><strong>通知预览</strong></div><span>Telegram</span></div><div className="telegram-chat"><div className="chat-date">今天</div><div className="chat-bubble"><div className="bot-name">MXRoute Mail Bot</div><pre>{preview.data || renderLocal(form.template)}</pre><time>刚刚</time></div></div><p>实际发送内容会根据邮件信息替换模板变量。</p></aside>
    </div>
  </div>
}
function split(value: string) { return value.split(',').map(v => v.trim()).filter(Boolean) }
function renderLocal(template: string) { const data: Record<string, string> = { subject: '三月服务账单已生成', 'from.name': 'MXRoute Billing', 'from.address': 'billing@mxroute.com', date: new Date().toLocaleString('zh-CN'), to: 'hello@example.com', 'body.text': '您好，三月份的服务账单已经生成。请登录账户中心查看详情。', 'attachments.length': '1', url: 'http://localhost:5173' }; return template.replace(/{{\s*([^}]+)\s*}}/g, (_, key: string) => data[key.trim()] ?? '') }
